version: '3.4'

services:
  redzone.api:
    container_name: redzone.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Port=5432;Database=OrderDb;User Id=admin;Password=admin1234;"
    depends_on:
      - orderdb
    ports:
      - "8000:80"

  orderdb:
    container_name: orderdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=OrderDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

